[package]
name = "sgx-runtime"
version = "2.0.0-alpha.6"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
serde        	  = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/serde-sgx" }

[dependencies.sp-application-crypto]
version = '2.0.0-alpha.6'
default-features = false
features = ["full_crypto"]

[dependencies.balances]
package = "pallet-balances"
version = '2.0.0-alpha.6'
default-features = false

[dependencies.timestamp]
package = "pallet-timestamp"
version = '2.0.0-alpha.6'
default-features = false

[dependencies.transaction-payment]
package = "pallet-transaction-payment"
version = '2.0.0-alpha.6'
default-features = false

[dependencies.sudo]
package = "pallet-sudo"
version = '2.0.0-alpha.6'
default-features = false

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
version = "1.3.0"
features = ["derive"]

[dependencies.sp-api]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.sp-std]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.sp-core]
version = '2.0.0-alpha.6'
default-features = false
features = ["full_crypto"]

[dependencies.sp-runtime]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.frame-support]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.system]
package = "frame-system"
version = '2.0.0-alpha.6'
default-features = false

[dependencies.sp-version]
version = '2.0.0-alpha.6'
default-features = false


