[package]
name = "sgx-runtime"
version = "2.0.0-alpha.6"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]

[dependencies.sp-application-crypto]
version = '2.0.0-alpha.6'
default-features = false
features = ["full_crypto"]

[dependencies.pallet-balances]
version = '2.0.0-alpha.6'
default-features = false

#[dependencies.pallet-indices]
#default-features = false

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
version = "1.3.0"
features = ["derive"]

[dependencies.sp-core]
version = '2.0.0-alpha.6'
default-features = false
features = ["full_crypto"]

[dependencies.sp-runtime]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.frame-support]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.frame-system]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.sp-version]
version = '2.0.0-alpha.6'
default-features = false


